; Script generated by Antigravity for Windownimator 2.1.0
; Requires Inno Setup (https://jrsoftware.org/isdl.php)

[Setup]
AppName=Windownimator
AppVersion=2.1.0
AppPublisher=arsenjkin459g
AppPublisherURL=https://github.com/arsenjkin459g-source/windownimator
AppSupportURL=https://github.com/arsenjkin459g-source/windownimator
AppUpdatesURL=https://github.com/arsenjkin459g-source/windownimator/releases
DefaultDirName={autopf}\Windownimator
DefaultGroupName=Windownimator
UninstallDisplayIcon={app}\Windownimator_v2.1.0.exe
OutputDir=dist
OutputBaseFilename=Windownimator_v2.1.0_Setup
SetupIconFile=windownimator.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\Windownimator_v2.1.0.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\Windownimator"; Filename: "{app}\Windownimator_v2.1.0.exe"; IconFilename: "{app}\Windownimator_v2.1.0.exe"
Name: "{autodesktop}\Windownimator"; Filename: "{app}\Windownimator_v2.1.0.exe"; Tasks: desktopicon; IconFilename: "{app}\Windownimator_v2.1.0.exe"

[Run]
Filename: "{app}\Windownimator_v2.1.0.exe"; Description: "{cm:LaunchProgram,Windownimator}"; Flags: postinstall nowait skipifsilent
