"""
Windownimator 2.0 — EXE Exporter
Generates a self-contained animation runner (native WinAPI dialogs) and
compiles it with PyInstaller.
"""

from __future__ import annotations
import base64
import json
import os
import shutil
import subprocess
import sys
import tempfile
from typing import Callable, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from core.animation import Animation

RUNNER_TEMPLATE = r'''# -*- coding: utf-8 -*-
"""Auto-generated by Windownimator 2.0 — uses REAL Windows dialogs."""
import os, sys, time, math, base64, tempfile, threading
import ctypes, ctypes.wintypes as wt

ANIMATION_DATA = {animation_json}
SOUND_FILES    = {sound_data}

FPS = 60; FRAME_DT = 1.0 / FPS
user32 = ctypes.windll.user32; kernel32 = ctypes.windll.kernel32
user32.GetWindowThreadProcessId.restype = wt.DWORD
user32.GetWindowThreadProcessId.argtypes = [wt.HWND, ctypes.POINTER(wt.DWORD)]
user32.IsWindowVisible.restype = wt.BOOL
user32.IsWindowVisible.argtypes = [wt.HWND]
user32.IsWindow.restype = wt.BOOL
user32.IsWindow.argtypes = [wt.HWND]
user32.SetWindowPos.restype = wt.BOOL
user32.SetWindowPos.argtypes = [wt.HWND, wt.HWND, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int, wt.UINT]
user32.PostMessageW.restype = wt.BOOL
user32.PostMessageW.argtypes = [wt.HWND, wt.UINT, wt.WPARAM, wt.LPARAM]
user32.MessageBoxW.restype = ctypes.c_int
user32.MessageBoxW.argtypes = [wt.HWND, wt.LPCWSTR, wt.LPCWSTR, wt.UINT]
user32.GetClassNameW.restype = ctypes.c_int
user32.GetClassNameW.argtypes = [wt.HWND, wt.LPWSTR, ctypes.c_int]
user32.EndDialog.restype = wt.BOOL
user32.EndDialog.argtypes = [wt.HWND, ctypes.c_int]
kernel32.GetCurrentThreadId.restype = wt.DWORD
kernel32.GetCurrentThreadId.argtypes = []

MB_ICONS = {{"info":0x40,"warning":0x30,"error":0x10,"question":0x20,"none":0}}
MB_BTNS  = {{"ok":0,"okcancel":1,"yesno":4,"yesnocancel":3,"retrycancel":5,"abortretryignore":2}}
SYS_SND  = {{"info":"SystemAsterisk","warning":"SystemExclamation","error":"SystemHand","question":"SystemQuestion"}}
SWP_NOSIZE=0x0001; SWP_NOACT=0x0010; TOPMOST=-1; WM_CLOSE=0x0010
EnumWP = ctypes.WINFUNCTYPE(ctypes.c_bool, wt.HWND, wt.LPARAM)
_tmp=None; _sp={{}}

def _exsnd():
    global _tmp,_sp
    if not SOUND_FILES: return
    _tmp=tempfile.mkdtemp(prefix="wnim_")
    for n,b in SOUND_FILES.items():
        p=os.path.join(_tmp,n); open(p,"wb").write(base64.b64decode(b)); _sp[n]=p

def _psnd(wo):
    sp=wo.get("sound_path"); ss=wo.get("system_sound") or wo.get("icon","")
    if sp:
        fn=os.path.basename(sp); rp=_sp.get(fn)
        if rp:
            try:
                import pygame.mixer as mx
                if not mx.get_init(): mx.init()
                mx.Sound(rp).play(); return
            except: pass
    sn=SYS_SND.get(ss)
    if sn:
        try: import winsound; winsound.PlaySound(sn,winsound.SND_ALIAS|winsound.SND_ASYNC)
        except: pass

def _stpsnd():
    try: import winsound; winsound.PlaySound(None,0)
    except: pass
    try:
        import pygame.mixer as mx
        if mx.get_init(): mx.stop()
    except: pass

def _ease(t,m):
    if m=="linear": return t
    if m=="ease_in": return t*t*t
    if m=="ease_out": u=1-t; return 1-u*u*u
    if m=="ease_in_out":
        if t<0.5: return 4*t*t*t
        u=2*t-2; return 1+u*u*u/2
    if m=="bounce":
        if t<1/2.75: return 7.5625*t*t
        elif t<2/2.75: t-=1.5/2.75; return 7.5625*t*t+0.75
        elif t<2.5/2.75: t-=2.25/2.75; return 7.5625*t*t+0.9375
        else: t-=2.625/2.75; return 7.5625*t*t+0.984375
    if m=="elastic":
        if t==0 or t==1: return t
        return math.pow(2,-10*t)*math.sin((t-0.075)*(2*math.pi)/0.3)+1
    return t

def _fhwnd(tid):
    f=[None]
    def cb(h,_):
        if user32.GetWindowThreadProcessId(h,None)==tid and user32.IsWindowVisible(h):
            f[0]=h; return False
        return True
    user32.EnumWindows(EnumWP(cb),0); return f[0]

class Dlg:
    def __init__(self,wo): self.wo=wo; self.hwnd=None; self._tid=None
    def open(self,x,y):
        threading.Thread(target=self._mb,daemon=True).start()
        dl=time.time()+2.0
        while time.time()<dl:
            if self._tid:
                h=_fhwnd(self._tid)
                if h: self.hwnd=h; break
            time.sleep(0.015)
        if self.hwnd:
            user32.SetWindowPos(self.hwnd,TOPMOST,x,y,0,0,SWP_NOSIZE|0x0040)
    def _mb(self):
        self._tid=kernel32.GetCurrentThreadId()
        ic=MB_ICONS.get(self.wo.get("icon","none"),0)
        bt=MB_BTNS.get(self.wo.get("buttons","ok"),0)
        user32.MessageBoxW(0,self.wo.get("message",""),self.wo.get("title",""),ic|bt|0x00040000)
    def move(self,x,y,w=0,h=0):
        if self.hwnd and user32.IsWindow(self.hwnd):
            if w>0 and h>0:
                user32.SetWindowPos(self.hwnd,TOPMOST,int(x),int(y),int(w),int(h),SWP_NOACT)
            else:
                user32.SetWindowPos(self.hwnd,TOPMOST,int(x),int(y),0,0,SWP_NOSIZE|SWP_NOACT)
    def close(self):
        if self.hwnd and user32.IsWindow(self.hwnd):
            user32.EndDialog(self.hwnd,0)
            user32.PostMessageW(self.hwnd,0x0111,1,0)
            user32.PostMessageW(self.hwnd,0x0111,2,0)
            user32.PostMessageW(self.hwnd,WM_CLOSE,0,0)
            self.hwnd=None
    def alive(self): return bool(self.hwnd and user32.IsWindow(self.hwnd))

def main():
    _exsnd()
    wins=ANIMATION_DATA.get("windows",[]); kfs=ANIMATION_DATA.get("keyframes",[])
    loop=ANIMATION_DATA.get("loop",False)
    if not wins or not kfs: return
    dlgs={{}}
    kf0=kfs[0]
    for wo in wins:
        wid=wo["id"]; s=kf0.get("states",{{}}).get(wid,{{"x":400,"y":300,"visible":True}})
        d=Dlg(wo); dlgs[wid]=d
        if s.get("visible",True): d.open(s.get("x",400),s.get("y",300)); time.sleep(0.06)
    for wo in wins:
        if wo.get("sound_start_kf_index",0)==0:
            threading.Thread(target=_psnd,args=(wo,),daemon=True).start()
    kf_idx=0; lc=0
    while True:
        if kf_idx+1>=len(kfs):
            if loop: kf_idx=0; lc+=1
            if not loop or lc>200: break
            continue
        kff=kfs[kf_idx]; kft=kfs[kf_idx+1]
        dur=kff.get("duration_ms",800)/1000.0; eas=kff.get("easing","ease_in_out")
        steps=max(1,int(dur*FPS))
        next_kf=kf_idx+1
        for wo in wins:
            if wo.get("sound_start_kf_index",0)==next_kf:
                threading.Thread(target=_psnd,args=(wo,),daemon=True).start()
        t0=time.perf_counter()
        for step in range(steps+1):
            t=step/steps
            for wo in wins:
                wid=wo["id"]; d=dlgs.get(wid)
                if not d: continue
                s0=kff.get("states",{{}}).get(wid,{{"x":400,"y":300}})
                s1=kft.get("states",{{}}).get(wid,{{"x":400,"y":300}})
                win_eas=s0.get("easing") or eas
                et=_ease(t,win_eas)
                x=int(s0.get("x",400)+(s1.get("x",400)-s0.get("x",400))*et)
                y=int(s0.get("y",300)+(s1.get("y",300)-s0.get("y",300))*et)
                v0=s0.get("visible",True); v1=s1.get("visible",True)
                if not v0 and v1 and t>0.3 and not d.alive():
                    nd=Dlg(wo); dlgs[wid]=nd
                    threading.Thread(target=nd.open,args=(x,y),daemon=True).start(); d=nd
                elif v0 and not v1 and t>0.7 and d.alive(): d.close()
                else: d.move(x,y)
            el=time.perf_counter()-t0; ex=(step+1)*FRAME_DT
            if ex-el>0: time.sleep(ex-el)
        hms=kff.get("hold_ms",0)
        if hms>0: time.sleep(hms/1000.0)
        kf_idx+=1
    for d in dlgs.values():
        try: d.close()
        except: pass
    _stpsnd()
    if _tmp:
        try: import shutil as sh; sh.rmtree(_tmp,ignore_errors=True)
        except: pass

if __name__=="__main__":
    main()
'''


def _encode_sounds(animation: "Animation") -> dict:
    sound_data = {}
    for w in animation.windows:
        if w.sound_path and os.path.exists(w.sound_path):
            fname = os.path.basename(w.sound_path)
            if fname not in sound_data:
                with open(w.sound_path, "rb") as f:
                    sound_data[fname] = base64.b64encode(f.read()).decode()
    return sound_data


def export_to_exe(
    animation: "Animation",
    output_dir: str,
    exe_name: Optional[str] = None,
    on_progress: Optional[Callable[[str], None]] = None,
) -> str:
    if exe_name is None:
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in animation.name)
        exe_name = safe or "animation"

    build_dir = tempfile.mkdtemp(prefix="wa_build_")

    try:
        runner_path = os.path.join(build_dir, "animation_runner.py")
        raw_json_str = json.dumps(animation.to_dict(), ensure_ascii=False)
        anim_py_dict = raw_json_str.replace("true", "True").replace("false", "False").replace("null", "None")
        sound_data  = _encode_sounds(animation)
        sound_json  = json.dumps(sound_data, ensure_ascii=False)

        script = RUNNER_TEMPLATE.format(
            animation_json=anim_py_dict,
            sound_data=sound_json,
        )
        with open(runner_path, "w", encoding="utf-8") as f:
            f.write(script)

        if on_progress:
            on_progress("📝 Скрипт создан...")

        if getattr(sys, "frozen", False):
            # Running inside compiled Windownimator.exe -> do NOT use sys.executable (which is Windownimator.exe)
            pyinstaller_bin = shutil.which("pyinstaller") or shutil.which("pyinstaller.exe")
            python_bin = shutil.which("python") or shutil.which("python.exe") or shutil.which("py")
            if pyinstaller_bin:
                cmd = [
                    pyinstaller_bin,
                    "--onefile", "--noconsole", "--clean",
                    f"--name={exe_name}",
                    f"--distpath={output_dir}",
                    f"--workpath={os.path.join(build_dir, 'build')}",
                    f"--specpath={build_dir}",
                    runner_path,
                ]
            elif python_bin:
                cmd = [
                    python_bin, "-m", "PyInstaller",
                    "--onefile", "--noconsole", "--clean",
                    f"--name={exe_name}",
                    f"--distpath={output_dir}",
                    f"--workpath={os.path.join(build_dir, 'build')}",
                    f"--specpath={build_dir}",
                    runner_path,
                ]
            else:
                raise RuntimeError(
                    "Утилита PyInstaller не найдена в системной переменной PATH.\n"
                    "Для экспорта из скомпилированной версии убедитесь, что в системе установлен Python и PyInstaller."
                )
        else:
            cmd = [
                sys.executable, "-m", "PyInstaller",
                "--onefile", "--noconsole", "--clean",
                f"--name={exe_name}",
                f"--distpath={output_dir}",
                f"--workpath={os.path.join(build_dir, 'build')}",
                f"--specpath={build_dir}",
                runner_path,
            ]

        if on_progress:
            on_progress("⚙️ Компиляция EXE (подождите)...")

        result = subprocess.run(cmd, capture_output=True, text=True, cwd=build_dir)

        if result.returncode != 0:
            raise RuntimeError(f"PyInstaller error:\n{result.stderr[-3000:]}")

        exe_path = os.path.join(output_dir, exe_name + ".exe")
        if not os.path.exists(exe_path):
            raise RuntimeError(f"EXE not found: {exe_path}")

        if on_progress:
            on_progress(f"✅ Готово: {exe_path}")

        return exe_path

    finally:
        shutil.rmtree(build_dir, ignore_errors=True)
